[package]
name = "admin_api"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = { version = "1.8.2", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.84.0"
base64 = "0.22.1"
lambda_http = "0.14.0"
lambda_runtime = "0.14.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
urlencoding = "2.1.3"
