[package]
name = "ddex_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "1.1.2", default-features = false, features = ['std'] }
prover_interface = { path = "../interface" }
ddex_schema = { path = "../../parser/ddex_schema"}

