services:
  builder:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /protocol-core
    volumes:
      - ../../../:/protocol-core
      - container_target:/protocol-core/target
      - container_node_modules:/protocol-core/contracts/node_modules
      - container_artifacts:/protocol-core/contracts/artifacts
      - container_cache:/protocol-core/contracts/cache
      - container_typechain:/protocol-core/contracts/typechain_types
    environment:
      - RPC_URL=${RPC_URL}
      - PROVING_SETUP=false
      - KURTOSIS_MNEMONIC=${KURTOSIS_MNEMONIC}
    command: ["/protocol-core/local_setup/dev_mode_network/scripts/setup/build.sh"]

  validator_node_1:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /protocol-core
    depends_on:
      builder:
        condition: service_completed_successfully
      ipfs:
        condition: service_started
    volumes:
      - ../../../:/protocol-core
      - container_target:/protocol-core/target
      - container_node_modules:/protocol-core/contracts/node_modules
      - container_artifacts:/protocol-core/contracts/artifacts
      - container_cache:/protocol-core/contracts/cache
      - container_typechain:/protocol-core/contracts/typechain_types
      - /protocol-core/validator_node/temp
    environment:
      - PRIVATE_KEY=${VALIDATOR_1_PK}
      - RPC_URL=${RPC_URL}
      - WS_URL=${WS_URL}
      - BEACON_RPC_URL=${BEACON_RPC_URL}
      - START_BLOCK=${START_BLOCK}
      - SEGMENT_LIMIT_PO2=${SEGMENT_LIMIT_PO2}
      - ENVIRONMENT=${ENVIRONMENT}
      - USERNAME=${USERNAME}
      - DISABLE_TELEMETRY=${DISABLE_TELEMETRY}
      - RISC0_DEV_MODE=1
      - LOCAL=true
      - IPFS_API_BASE_URL=http://ipfs:5001
    command: ["tail", "-f", "/dev/null"]


  validator_node_2:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /protocol-core
    depends_on:
      builder:
        condition: service_completed_successfully
      ipfs:
        condition: service_started
    volumes:
      - ../../../:/protocol-core
      - container_target:/protocol-core/target
      - container_node_modules:/protocol-core/contracts/node_modules
      - container_artifacts:/protocol-core/contracts/artifacts
      - container_cache:/protocol-core/contracts/cache
      - container_typechain:/protocol-core/contracts/typechain_types
      - /protocol-core/validator_node/temp
    environment:
      - PRIVATE_KEY=${VALIDATOR_2_PK}
      - RPC_URL=${RPC_URL}
      - WS_URL=${WS_URL}
      - BEACON_RPC_URL=${BEACON_RPC_URL}
      - START_BLOCK=${START_BLOCK}
      - SEGMENT_LIMIT_PO2=${SEGMENT_LIMIT_PO2}
      - ENVIRONMENT=${ENVIRONMENT}
      - USERNAME=${USERNAME}
      - DISABLE_TELEMETRY=${DISABLE_TELEMETRY}
      - RISC0_DEV_MODE=1
      - LOCAL=true
      - IPFS_API_BASE_URL=http://ipfs:5001
    command: ["tail", "-f", "/dev/null"]

  validator_node_3:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /protocol-core
    depends_on:
      builder:
        condition: service_completed_successfully
      ipfs:
        condition: service_started
    volumes:
      - ../../../:/protocol-core
      - container_target:/protocol-core/target
      - container_node_modules:/protocol-core/contracts/node_modules
      - container_artifacts:/protocol-core/contracts/artifacts
      - container_cache:/protocol-core/contracts/cache
      - container_typechain:/protocol-core/contracts/typechain_types
      - /protocol-core/validator_node/temp
    environment:
      - PRIVATE_KEY=${VALIDATOR_3_PK}
      - RPC_URL=${RPC_URL}
      - WS_URL=${WS_URL}
      - BEACON_RPC_URL=${BEACON_RPC_URL}
      - START_BLOCK=${START_BLOCK}
      - SEGMENT_LIMIT_PO2=${SEGMENT_LIMIT_PO2}
      - ENVIRONMENT=${ENVIRONMENT}
      - USERNAME=${USERNAME}
      - DISABLE_TELEMETRY=${DISABLE_TELEMETRY}
      - RISC0_DEV_MODE=1
      - LOCAL=true
      - IPFS_API_BASE_URL=http://ipfs:5001
    command: ["tail", "-f", "/dev/null"]


  owen:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /protocol-core
    depends_on:
      builder:
        condition: service_completed_successfully
      ipfs:
        condition: service_started
    volumes:
      - ../../../:/protocol-core
      - container_target:/protocol-core/target
      - container_node_modules:/protocol-core/contracts/node_modules
      - container_artifacts:/protocol-core/contracts/artifacts
      - container_cache:/protocol-core/contracts/cache
      - container_typechain:/protocol-core/contracts/typechain_types
    environment:
      - PRIVATE_KEY=${DATA_PROVIDER_PK}
      - RPC_URL=${RPC_URL}
      - ENVIRONMENT=${ENVIRONMENT}
      - DISABLE_TELEMETRY=${DISABLE_TELEMETRY}
      - LOCAL_IPFS=true
      - LOCAL=true
      - USERNAME=${USERNAME}
      - OUTPUT_FILES_DIR=./output_files
      - IPFS_API_BASE_URL=http://ipfs:5001
    command: ["tail", "-f", "/dev/null"]


  ipfs:
    image: ipfs/kubo:latest
    ports:
      - "5001:5001"

volumes:
  container_target:
  container_node_modules:
  container_artifacts:
  container_cache:
  container_typechain: