Transform: AWS::Serverless-2016-10-31

Parameters:
  MessagesBucketName:
    Description: "Bucket must have EventBridge enabled!"
    Type: String
  CreateNewBucket:
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
  MessageStatusTableName:
    Type: String
  TriggerFilePattern:
    Type: String
  OwenLambdaScheduleRateMin:
    Type: String
  ProcessingStatusIndexName:
    Type: String
  MessageFolderAttributeName:
    Type: String
  ProcessingStatusAttributeName:
    Type: String
  CreatedTimestampAttributeName:
    Type: String
  UpdatedTimestampAttributeName:
    Type: String
  UnprocessedStatusValue:
    Type: String
  ProcessedStatusValue:
    Type: String
  ReservedStatusValue:
    Type: String
  RejectedStatusValue:
    Type: String
  MessagePerBlob:
    Type: String
  OutputFilesDir:
    Type: String
  InputFilesDir:
    Type: String
  Environment:
    Type: String
  OwenUsername:
    Type: String
  OwenLambdaSecretsName:
    Type: String
  DdexSequencerAddress:
    Type: String
    Default: ""

Conditions:
  ShouldCreateNewBucket: !Equals [!Ref CreateNewBucket, "true"]
  OverwriteDdexSequencerAddress: !Not [!Equals [!Ref DdexSequencerAddress, ""]]

Resources:
  NewUploadsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 240
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt NewUploadsDeadLetterQueue.Arn
        maxReceiveCount: 1

  NewUploadsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 20160 min | 336 h | 14 days

  MessagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Condition: ShouldCreateNewBucket
    Properties:
      BucketName: !Ref MessagesBucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  NewUploadEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        resources:
          - !Sub "arn:aws:s3:::${MessagesBucketName}"
        detail:
          object:
            key:
              - { "wildcard": !Sub "*${TriggerFilePattern}*" }
      State: ENABLED
      Targets:
        - Arn: !GetAtt NewUploadsQueue.Arn
          Id: NewUploadsQueueTarget

  NewUploadsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: NewUploadsQueue
        - Ref: NewUploadsDeadLetterQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt NewUploadsQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !GetAtt NewUploadEventRule.Arn

  OwenLambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref OwenLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt OwenLambdaScheduledRule.Arn

  OwenLambdaScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      # Name: "OwenLambdaScheduledRuleStage"
      ScheduleExpression: !Sub "rate(${OwenLambdaScheduleRateMin} minutes)"
      State: ENABLED
      Targets:
        - Arn: !GetAtt OwenLambda.Arn
          Id: "OwenLambdaTarget"
          RetryPolicy:
            MaximumRetryAttempts: 0 # Disable automatic retries

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}/index/*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${MessagesBucketName}"
                  - !Sub "arn:aws:s3:::${MessagesBucketName}/*"
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref OwenLambdaSecrets

  OwenLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt LambdaExecutionRole.Arn
      CodeUri: ../../target/lambda/owen_lambda
      Runtime: "provided.al2023"
      Architectures:
        - x86_64
      Handler: bootstrap
      MemorySize: 512
      Timeout: 600
      AutoPublishAlias: OwenLambdaAlias
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Environment:
        Variables:
          MESSAGE_BUCKET_PREFIX: "revelator"
          FALLBACK_BUCKET_NAME: "empty"
          MESSAGE_STATUS_TABLE_NAME: !Ref MessageStatusTableName
          PROCESSING_STATUS_INDEX_NAME: !Ref ProcessingStatusIndexName
          MESSAGE_FOLDER_ATTRIBUTE_NAME: !Ref MessageFolderAttributeName
          PROCESSING_STATUS_ATTRIBUTE_NAME: !Ref ProcessingStatusAttributeName
          MESSAGES_BUCKET_NAME: !Ref MessagesBucketName
          UNPROCESSED_STATUS_VALUE: !Ref UnprocessedStatusValue
          PROCESSED_STATUS_VALUE: !Ref ProcessedStatusValue
          RESERVED_STATUS_VALUE: !Ref ReservedStatusValue
          REJECTED_STATUS_VALUE: !Ref RejectedStatusValue
          MESSAGES_PER_BLOB: !Ref MessagePerBlob
          INPUT_FILES_DIR: !Ref InputFilesDir
          OUTPUT_FILES_DIR: !Ref OutputFilesDir
          ENVIRONMENT: !Ref Environment
          USERNAME: !Ref OwenUsername
          OWEN_LAMBDA_SECRETS_NAME: !Ref OwenLambdaSecretsName
          DDEX_SEQUENCER_ADDRESS: !If
            - OverwriteDdexSequencerAddress
            - !Ref DdexSequencerAddress
            - !Ref "AWS::NoValue"

  OwenLambdaSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref OwenLambdaSecretsName
      Description: "Environmental variables with sensitive data for OwenLambda"
      # !!! Set those manually in your AWS Console after the deployment!!!
      # !!! Do not edit this line here directly !!!
      SecretString: '{"RPC_URL": "your-rpc-url", "PRIVATE_KEY": "your-private-key" }'

  QueueConsumerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../target/lambda/aws_queue_consumer
      Runtime: "provided.al2023"
      Architectures:
        - x86_64
      Handler: bootstrap
      MemorySize: 128
      Environment:
        Variables:
          MESSAGE_STATUS_TABLE_NAME: !Ref MessageStatusTableName
          UNPROCESSED_STATUS_VALUE: !Ref UnprocessedStatusValue
          CREATED_TIMESTAMP_ATTRIBUTE_NAME: !Ref CreatedTimestampAttributeName
          UPDATED_TIMESTAMP_ATTRIBUTE_NAME: !Ref UpdatedTimestampAttributeName
          MESSAGE_FOLDER_ATTRIBUTE_NAME: !Ref MessageFolderAttributeName
          PROCESSING_STATUS_ATTRIBUTE_NAME: !Ref ProcessingStatusAttributeName
      Policies:
        - Statement:
            - Effect: Allow
              Action: "dynamodb:PutItem"
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}"
      Events:
        NewMessageSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NewUploadsQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 3

  MessageStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref MessageStatusTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: !Ref MessageFolderAttributeName
          AttributeType: S
        - AttributeName: !Ref CreatedTimestampAttributeName
          AttributeType: N
        - AttributeName: !Ref ProcessingStatusAttributeName
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref MessageFolderAttributeName
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Ref ProcessingStatusIndexName
          KeySchema:
            - AttributeName: !Ref ProcessingStatusAttributeName
              KeyType: HASH
            - AttributeName: !Ref CreatedTimestampAttributeName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
