Transform: AWS::Serverless-2016-10-31

Parameters:
  MessagesBucketName:
    Description: "Bucket must have EventBridge enabled!"
    Type: String
  CreateNewBucket:
    Default: "false"
    Type: String
    AllowedValues: ["true", "false"]
  MessageStatusTableName:
    Type: String
  TriggerFilePattern:
    Type: String
  ProcessingStatusIndexName:
    Type: String
  MessageFolderAttributeName:
    Type: String
  ProcessingStatusAttributeName:
    Type: String
  CreatedTimestampAttributeName:
    Type: String
  UpdatedTimestampAttributeName:
    Type: String
  UnprocessedStatusValue:
    Type: String
  MessagePerBlob:
    Type: String
  Environment:
    Type: String
  OwenLambdaSecretsName:
    Type: String
  DdexSequencerAddress:
    Type: String
    Default: ""
  StorachaBridgeUrl:
    Type: String
    Default: ""
  BlobsTempStorageBucketPrefix:
    Default: owen-blobs-temp-storage
    Type: String

Conditions:
  ShouldCreateNewBucket: !Equals [!Ref CreateNewBucket, "true"]

Resources:
  NewUploadsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 240
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt NewUploadsDeadLetterQueue.Arn
        maxReceiveCount: 1

  NewUploadsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 20160 min | 336 h | 14 days

  MessagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Condition: ShouldCreateNewBucket
    Properties:
      BucketName: !Ref MessagesBucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  NewUploadEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        resources:
          - !Sub "arn:aws:s3:::${MessagesBucketName}"
        detail:
          object:
            key:
              - { "wildcard": !Sub "*${TriggerFilePattern}*" }
      State: ENABLED
      Targets:
        - Arn: !GetAtt NewUploadsQueue.Arn
          Id: NewUploadsQueueTarget

  NewUploadsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: NewUploadsQueue
        - Ref: NewUploadsDeadLetterQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt NewUploadsQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !GetAtt NewUploadEventRule.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: LambdaInlinePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:UpdateItem
                Resource:
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}"
                  - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}/index/*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${MessagesBucketName}"
                  - !Sub "arn:aws:s3:::${MessagesBucketName}/*"
              - Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref OwenLambdaSecrets

  OwenLambdaSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref OwenLambdaSecretsName
      Description: "Environmental variables with sensitive data for OwenLambda"
      # !!! Set those manually in your AWS Console after the deployment!!!
      # !!! Do not edit this line here directly !!!
      SecretString: '{"RPC_URL": "your-rpc-url", "PRIVATE_KEY": "your-private-key" }'

  QueueConsumerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../target/lambda/aws_queue_consumer
      Runtime: "provided.al2023"
      Architectures:
        - x86_64
      Handler: bootstrap
      MemorySize: 128
      Environment:
        Variables:
          MESSAGE_STATUS_TABLE_NAME: !Ref MessageStatusTableName
          UNPROCESSED_STATUS_VALUE: !Ref UnprocessedStatusValue
          CREATED_TIMESTAMP_ATTRIBUTE_NAME: !Ref CreatedTimestampAttributeName
          UPDATED_TIMESTAMP_ATTRIBUTE_NAME: !Ref UpdatedTimestampAttributeName
          MESSAGE_FOLDER_ATTRIBUTE_NAME: !Ref MessageFolderAttributeName
          PROCESSING_STATUS_ATTRIBUTE_NAME: !Ref ProcessingStatusAttributeName
      Policies:
        - Statement:
            - Effect: Allow
              Action: "dynamodb:PutItem"
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}"
      Events:
        NewMessageSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NewUploadsQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 3

  MessageStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref MessageStatusTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: !Ref MessageFolderAttributeName
          AttributeType: S
        - AttributeName: !Ref CreatedTimestampAttributeName
          AttributeType: N
        - AttributeName: !Ref ProcessingStatusAttributeName
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref MessageFolderAttributeName
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Ref ProcessingStatusIndexName
          KeySchema:
            - AttributeName: !Ref ProcessingStatusAttributeName
              KeyType: HASH
            - AttributeName: !Ref CreatedTimestampAttributeName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  OwenOne:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/owen.yml
      Parameters:
        LambdaScheduleRateMin: "8"
        MessagesBucketName: !Ref MessagesBucketName
        MessageStatusTableName: !Ref MessageStatusTableName
        MessagePerBlob: !Ref MessagePerBlob
        Environment: !Ref Environment
        OwenUsername: !Sub "owen_${Environment}_lambda_1"
        OwenLambdaSecretsName: !Ref OwenLambdaSecretsName
        DdexSequencerAddress: !Ref DdexSequencerAddress
        LambdaExecutionRoleArn: !GetAtt LambdaExecutionRole.Arn
        ProcessingStatusAttributeName: !Ref ProcessingStatusAttributeName
        MessageFolderAttributeName: !Ref MessageFolderAttributeName
        UnprocessedStatusValue: !Ref UnprocessedStatusValue
        StorachaBridgeUrl: !Ref StorachaBridgeUrl
        OwenBlobsQueueUrl: !GetAtt OwenBlobsQueue.Outputs.OwenBlobsQueueUrl
        BlobsTempStorageBucketName: !Sub "${BlobsTempStorageBucketPrefix}-${Environment}"

  OwenTwo:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/owen.yml
      Parameters:
        LambdaScheduleRateMin: "8"
        MessagesBucketName: !Ref MessagesBucketName
        MessageStatusTableName: !Ref MessageStatusTableName
        MessagePerBlob: !Ref MessagePerBlob
        Environment: !Ref Environment
        OwenUsername: !Sub "owen_${Environment}_lambda_2"
        OwenLambdaSecretsName: !Ref OwenLambdaSecretsName
        DdexSequencerAddress: !Ref DdexSequencerAddress
        LambdaExecutionRoleArn: !GetAtt LambdaExecutionRole.Arn
        ProcessingStatusAttributeName: !Ref ProcessingStatusAttributeName
        MessageFolderAttributeName: !Ref MessageFolderAttributeName
        UnprocessedStatusValue: !Ref UnprocessedStatusValue
        StorachaBridgeUrl: !Ref StorachaBridgeUrl
        OwenBlobsQueueUrl: !GetAtt OwenBlobsQueue.Outputs.OwenBlobsQueueUrl
        BlobsTempStorageBucketName: !Sub "${BlobsTempStorageBucketPrefix}-${Environment}"

  OwenThree:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/owen.yml
      Parameters:
        LambdaScheduleRateMin: "8"
        MessagesBucketName: !Ref MessagesBucketName
        MessageStatusTableName: !Ref MessageStatusTableName
        MessagePerBlob: !Ref MessagePerBlob
        Environment: !Ref Environment
        OwenUsername: !Sub "owen_${Environment}_lambda_3"
        OwenLambdaSecretsName: !Ref OwenLambdaSecretsName
        DdexSequencerAddress: !Ref DdexSequencerAddress
        LambdaExecutionRoleArn: !GetAtt LambdaExecutionRole.Arn
        ProcessingStatusAttributeName: !Ref ProcessingStatusAttributeName
        MessageFolderAttributeName: !Ref MessageFolderAttributeName
        UnprocessedStatusValue: !Ref UnprocessedStatusValue
        StorachaBridgeUrl: !Ref StorachaBridgeUrl
        OwenBlobsQueueUrl: !GetAtt OwenBlobsQueue.Outputs.OwenBlobsQueueUrl
        BlobsTempStorageBucketName: !Sub "${BlobsTempStorageBucketPrefix}-${Environment}"

  OwenBlobsQueue:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./resources/owen-blobs-queue.yml
      Parameters:
        BlobsTempStorageBucketName: !Sub "${BlobsTempStorageBucketPrefix}-${Environment}"
