[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "1.1.2" }
dotenvy = "0.15.7"

[package.metadata.risc0]
methods = ["guest"]

[dependencies]
prover_interface = { path = "./interface" }
