[package]
name = "prover"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "2.3.1" }
dotenvy = { workspace = true }
risc0-build-ethereum = "2.2.2"

[package.metadata.risc0]
methods = ["guest"]

[dependencies]
prover_interface = { path = "./interface" }
