Transform: AWS::Serverless-2016-10-31

Parameters:
  MessagesBucketName:
    Type: String
  MessageStatusTableName:
    Type: String
  TriggerFilePattern:
    Type: String
  OwenLambdaScheduleRateMin:
    Type: String
  ProcessingStatusIndexName:
    Type: String
  MessageFolderAttributeName:
    Type: String
  ProcessingStatusAttributeName:
    Type: String
  CreatedTimestampAttributeName:
    Type: String
  UpdatedTimestampAttributeName:
    Type: String
  UnprocessedStatusValue:
    Type: String
  ProcessedStatusValue:
    Type: String
  MessagePerBlob:
    Type: String
  DefaultIpfsInterface:
    Type: String
  OutputFilesDir:
    Type: String
  InputFilesDir:
    Type: String
  Environment:
    Type: String
  OwenUsername:
    Type: String
  OwenLambdaSecretsName:
    Type: String

Resources:
  NewUploadsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 240
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt NewUploadsDeadLetterQueue.Arn
        maxReceiveCount: 1

  NewUploadsDeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 20160 min | 336 h | 14 days

  MessagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Ref MessagesBucketName
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  NewUploadEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.s3
        detail-type:
          - Object Created
        resources:
          - !GetAtt MessagesBucket.Arn
        detail:
          object:
            key:
              - { "wildcard": !Sub "*${TriggerFilePattern}*" }
      State: ENABLED
      Targets:
        - Arn: !GetAtt NewUploadsQueue.Arn
          Id: NewUploadsQueueTarget

  NewUploadsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: NewUploadsQueue
        - Ref: NewUploadsDeadLetterQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt NewUploadsQueue.Arn
            Condition:
              ArnEquals:
                "aws:SourceArn": !GetAtt NewUploadEventRule.Arn

  OwenLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../target/lambda/owen_lambda
      Runtime: "provided.al2023"
      Architectures:
        - x86_64
      Handler: bootstrap
      MemorySize: 128
      Timeout: 20
      Environment:
        Variables:
          MESSAGE_STATUS_TABLE_NAME: !Ref MessageStatusTableName
          PROCESSING_STATUS_INDEX_NAME: !Ref ProcessingStatusIndexName
          MESSAGE_FOLDER_ATTRIBUTE_NAME: !Ref MessageFolderAttributeName
          PROCESSING_STATUS_ATTRIBUTE_NAME: !Ref ProcessingStatusAttributeName
          MESSAGES_BUCKET_NAME: !Ref MessagesBucketName
          UNPROCESSED_STATUS_VALUE: !Ref UnprocessedStatusValue
          PROCESSED_STATUS_VALUE: !Ref ProcessedStatusValue
          MESSAGES_PER_BLOB: !Ref MessagePerBlob
          DEFAULT_IPFS_INTERFACE: !Ref DefaultIpfsInterface
          INPUT_FILES_DIR: !Ref InputFilesDir
          OUTPUT_FILES_DIR: !Ref OutputFilesDir
          ENVIRONMENT: !Ref Environment
          USERNAME: !Ref OwenUsername
          OWEN_LAMBDA_SECRETS_NAME: !Ref OwenLambdaSecretsName
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:Query
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}/index/*"
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:ListBucket
              Resource:
                - !GetAtt MessagesBucket.Arn
                - !Sub "${MessagesBucket.Arn}/*"
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Ref OwenLambdaSecrets
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Sub "rate(${OwenLambdaScheduleRateMin} minutes)"

  OwenLambdaSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Ref OwenLambdaSecretsName
      Description: "Environmental variables with sensitive data for OwenLambda"
      # !!! Set those manually in your AWS Console after the deployment!!!
      # !!! Do not edit this line here directly !!!
      SecretString: '{"RPC_URL": "your-rpc-url", "PRIVATE_KEY": "your-private-key", "PINATA_JWT": "your-pinata-jwt", "IPFS_KUBO_URL": "your-kubo-url" }'

  QueueConsumerLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../../aws-queue-consumer/target/lambda/queue-consumer
      Runtime: "provided.al2023"
      Architectures:
        - x86_64
      Handler: bootstrap
      MemorySize: 128
      Environment:
        Variables:
          MESSAGE_STATUS_TABLE_NAME: !Ref MessageStatusTableName
          UNPROCESSED_STATUS_VALUE: !Ref UnprocessedStatusValue
          CREATED_TIMESTAMP_ATTRIBUTE_NAME: !Ref CreatedTimestampAttributeName
          UPDATED_TIMESTAMP_ATTRIBUTE_NAME: !Ref UpdatedTimestampAttributeName
          MESSAGE_FOLDER_ATTRIBUTE_NAME: !Ref MessageFolderAttributeName
          PROCESSING_STATUS_ATTRIBUTE_NAME: !Ref ProcessingStatusAttributeName
      Policies:
        - Statement:
            - Effect: Allow
              Action: "dynamodb:PutItem"
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${MessageStatusTableName}"
      Events:
        NewMessageSQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt NewUploadsQueue.Arn
            BatchSize: 10
            MaximumBatchingWindowInSeconds: 3

  MessageStatusTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref MessageStatusTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: !Ref MessageFolderAttributeName
          AttributeType: S
        - AttributeName: !Ref CreatedTimestampAttributeName
          AttributeType: N
        - AttributeName: !Ref ProcessingStatusAttributeName
          AttributeType: S
      KeySchema:
        - AttributeName: !Ref MessageFolderAttributeName
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: !Ref ProcessingStatusIndexName
          KeySchema:
            - AttributeName: !Ref ProcessingStatusAttributeName
              KeyType: HASH
            - AttributeName: !Ref CreatedTimestampAttributeName
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
