Transform: AWS::Serverless-2016-10-31

Parameters:
  BucketName:
    Type: String

Resources:
  ValidatorCluster:
    Type: AWS::ECS::Cluster

  ValidatorTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: GpuTaskDefinition
      RequiresCompatibilities:
        - EC2
      Cpu: "4096"
      Memory: "16384"
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      ContainerDefinitions:
        - Name: validator-container
          Image: "nvidia/cuda:latest"
          Memory: 4096
          Cpu: 1024
          ResourceRequirements:
            - Type: GPU
              Value: "1"
          Essential: true

  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ECSExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - ecs:CreateCluster
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  ECSInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: g4dn.xlarge
      ImageId: ami-06835d15c4de57810
      SecurityGroupIds:
        - !Ref ECSSecurityGroup
      SubnetId: !Ref PublicSubnet
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo yum install -y ecs-init
          sudo systemctl enable --now ecs
          sudo yum install -y nvidia-driver-latest-dkms
          sudo reboot

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow internet access
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: "-1"
          CidrIp: 0.0.0.0/0

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
