[package]
name = "prover_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = "2.2.0"
serde = "1.0.219"
ddex_parser = { path = "../../ddex_parser" }
alloy-sol-types = "1.3.0"
alloy-contract = "1.0.22"
alloy-primitives = "1.3.0"
