[package]
name = "prover_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = "2.0.2"
serde = "1.0"
ddex_parser = { path = "../../ddex_parser" }
alloy-sol-types = "0.8.18"
alloy-contract = "0.9.2"
alloy-primitives = "0.8.18"
