name: "Deploy Validator Node infrastructure to AWS environment"

on:
  push:
    branches: [master]
    paths:
      - "aws/validator-infra/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy-validator-infra:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAM_WORKFLOW_ROLE_PROTOCOL }}
          role-session-name: protocol-core-validator-infra-${{ github.run_id }}
          role-duration-seconds: 1200

      - name: "Deploy AWS Cloud Formation template"
        working-directory: aws/validator-infra
        run: make deploy-infra
