name: "Deploy OWEN (with Account Abstraction integration) to AWS dev environment"

# on:
#   push:
#     branches: [master]
#     paths:
#       - "owen/**"
#       - "prover/**"
#       - "aws/owen-infra/**"
#       - "aws/aws_queue_consumer/**"
#       - "aws/blobs_batch_sender/**"
on:
  push:
    branches: [owen-aa-integration]

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-owen-aa-template.yml
    with:
      env: "dev"
      run_id: ${{ github.run_id }}
    secrets: inherit
