name: "Deploy Owen infrastructure and code to AWS dev environment"

on:
  push:
    branches: [master]
    paths:
      - "owen/**"
      - "prover/**"
      - "aws/owen-infra/**"
      - "aws/aws_queue_consumer/**"
      - "aws/blobs_batch_sender/**"

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-owen-template.yml
    with:
      env: "dev"
      run_id: ${{ github.run_id }}
    secrets: inherit
