name: "Deploy Owen infrastructure and code to AWS"

on:
  # push:
  #   branches: [master]
  #   paths:
  #     - "owen/**"
  pull_request:
    paths:
      - "owen/**"

permissions:
  id-token: write
  contents: read

jobs:
  service-deploy:
    runs-on: ubuntu-latest
    container: amazonlinux:latest
    timeout-minutes: 30

    steps:
      - name: "Install rust and cargo"
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo 'source $HOME/.cargo/env' >> ~/.bashrc
          source $HOME/.cargo/env

      - name: "Install dependencies with dnf"
        run: dnf install -y gcc gcc-c++ glibc-devel make python3-pip openssl openssl-devel tar gzip git

      - name: "Install cargo-lambda"
        run: pip3 install cargo-lambda

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: "Checkout"
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: "Is there a node?"
        working-directory: owen
        run: node -v

      - name: "Build aws-queue-consumer"
        working-directory: aws-queue-consumer
        run: |
          source $HOME/.cargo/env
          cargo lambda build --release

      - name: "Build owen_lambda"
        working-directory: owen
        run: |
          source $HOME/.cargo/env
          cargo lambda build --release --bin owen_lambda --features aws-integration --compiler cargo

      - name: "See queue consumer files"
        working-directory: aws-queue-consumer
        run: ls

      - name: "See owen files"
        working-directory: owen
        run: ls
      # - name: "Deploy AWS Cloud Formation template"
      #   working-directory: owen/aws/deploy-infra
      #   run: make deploy-infra-dev
