name: "Deploy Owen infrastructure and code to AWS"

on:
  # push:
  #   branches: [master]
  #   paths:
  #     - "owen/**"
  pull_request:
    paths:
      - "owen/**"

permissions:
  id-token: write
  contents: read

jobs:
  service-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.IAM_WORKFLOW_ROLE }}
          role-session-name: protocol-core-session-id-${{ github.run_id }}
          role-duration-seconds: 1200

      - name: "Deploy AWS Cloud Formation template"
        working-directory: aws-queue-consumer
        run: cargo build --release

      - name: "Deploy AWS Cloud Formation template"
        working-directory: owen/aws/deploy-infra
        run: make deploy-infra-dev
