name: Publish contracts package to NPM
on:
  release:
    types:
      - created

permissions:
  id-token: write
  contents: read

jobs:
  Publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: |
      startsWith(github.ref, 'refs/tags/@originalworks/protocol-core-contracts') &&
      !contains(github.ref, '-alpha.')

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: "Setup node"
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          scope: "@originalworks"

      - name: "Setup environment"
        working-directory: contracts
        run: npm ci

      - name: "Build"
        working-directory: contracts/packages/contracts
        run: npm run build

      - name: "Publish"
        working-directory: contracts/packages/contracts
        run: npm publish --access public
