name: Create Owen Release

on:
  push:
    tags:
      - "owen@*"

jobs:
  release:
    uses: ./.github/workflows/_release-template.yml
    with:
      tag: ${{ github.ref }}
    secrets: inherit

  deploy:
    needs: release
    uses: ./.github/workflows/_deploy-owen-aa-template.yml
    with:
      env: "stage"
      run_id: ${{ github.run_id }}
    secrets:
      aws_iam_workflow_role: ${{ secrets.IAM_WORKFLOW_ROLE_REVELATOR_PROD }}
