name: Create Validator Release

on:
  push:
    tags:
      - "validator_node@*"

jobs:
  release:
    uses: ./.github/workflows/_release-template.yml
    with:
      tag: ${{ github.ref }}
    secrets:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.SENTRY_ORG }}